name: Flutter CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  android:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter pub get
      - run: |
          # build release apks

          ## environment setup

          app_ver=$(grep 'version:' pubspec.yaml)
          app_ver=$(echo "${app_ver/'version:'/}" | xargs)
          app_ver="${app_ver%%+*}"
          echo "v$app_ver"
          echo "app_ver=$app_ver" >> $GITHUB_ENV

          mkdir artifacts && {
            ARTIFACTS_PATH="$GITHUB_WORKSPACE/artifacts"
            echo "ARTIFACTS_PATH=$ARTIFACTS_PATH" >> $GITHUB_ENV
          }
          
          ## build

          flutter pub get

          flutter build apk --release --split-per-abi
          (cd ./build/app/outputs/flutter-apk/ && {
            mv ./app-arm64-v8a-release.apk "$ARTIFACTS_PATH/$APP_NAME-$app_ver-arm64-v8a.apk"
            mv ./app-armeabi-v7a-release.apk "$ARTIFACTS_PATH/$APP_NAME-$app_ver-armeabi-v7a.apk"
            mv ./app-x86_64-release.apk "$ARTIFACTS_PATH/$APP_NAME-$app_ver-x86_64.apk"
          })

          flutter build apk --release
          (cd ./build/app/outputs/flutter-apk/ &&
            mv ./app-release.apk "$ARTIFACTS_PATH/$APP_NAME-$app_ver-universal.apk"
          )

          rm -rf ./build/app/outputs/apk # remove dupe apk dir
        shell: bash
        env:
          APP_NAME: "otex_preview_app"

      - name: Upload Android Artifacts to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: ${{ env.ARTIFACTS_PATH }}/*